### ISSUE TITLE
Update to a more recent dev build?

### ISSUE THREAD

**Issue by tobilg** [holdenmatt/duckdb-wasm-kit#15]
Would it be possible to eventually update duckdb-wasm-kit to a more recent duckdb-wasm dev build? Unfortunately, the versioning doesn't really match the one from DuckDB itself or duckdb-node. I already asked many times in the Discord channel if new non-dev versions can be release upon DuckDB upstream releases, but to no avail yet...

Thanks a lot in advance!

**Comment by holdenmatt** [comment]
Sure, I just published duckdb-wasm-kit 0.1.32 to npm, which uses the most recent 1.28.1-dev195.0 dev build.

Can you try it and let me know if anything seems off for you?

Since the duckdb-wasm library is a moving target, I wonder if I should make it a peer dependency instead so developers like you are free to pick a version (dev or stable) independently of this helper library? I haven't tried that before, but I suspect it would work better since the types/functions I'm using probably change rarely.

Any opinion on whether that would work better for you?

**Comment by tobilg** [comment]
Hey, sorry for the late feedback! In general, I think the idea of having it as a peer dependency is good. I Have a slight concern though that e.g. if they update the Arrow dependency, things break (I had that case already)...

**Comment by tobilg** [comment]
Hi, sorry to bother you again, but yesterday the 1.0.0 version of DuckDB was released, and this is apparently the respective DuckDB WASM version: https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.1-dev211.0 Could you eventually update the repo again? Thanks a lot in advance!

**Comment by holdenmatt** [comment]
Sure, updated and confirmed it's using duckdb v1.0.0, published here:
https://www.npmjs.com/package/duckdb-wasm-kit

I also made apache-arrow a peer dep, so I shouldn't need to keep the versions in sync, it'll use whatever version duckdb is using. I left duckdb-wasm as a dependency for now.

I've tested it in production and seems to be working, but let me know if you see any issues after upgrading. thanks!

**Comment by tobilg** [comment]
Thank you very much, much appreciated! I can confirm it works for me as well. 

There was a fix for attaching remote databases in https://github.com/duckdb/duckdb-wasm/pull/1756 which is apparently included in https://www.npmjs.com/package/@duckdb/duckdb-wasm/v/1.28.1-dev215.0 now. Shall I create a MR?

**Comment by tobilg** [comment]
I created a MR at #16 Thanks!
